In [2]:
import numpy as np

In [3]:
a=np.array([10,20,30,40,50])
print(a)
print(type(a))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [4]:
print(a[0])
print(a[2])

10
30


In [7]:
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.size)

(5,)
1
int64
5


In [ ]:
b=np.array([
    [1,2,3],
    [4,5,6]
])

print(b.shape)   #shpae -> row by column
print(b.ndim)  #Dimension


(2, 3)
2


In [11]:
prices =np.array([100,200,300])
print(prices*2)

[200 400 600]


In [17]:
###Inititlizing Array

In [18]:
#Zero
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
print(np.ones((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [20]:
print(np.full((3,4),7))

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
###Ranges

In [ ]:
#Arange
print(np.arange(5))
print(np.arange(2,9))
print(np.arange(2,9,3))

[0 1 2 3 4]
[2 3 4 5 6 7 8]
[2 5 8]


In [27]:
#Linspace
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [28]:
###Random arrays

In [ ]:
print(np.random.rand(3))     #Alawyas 0 to one

[0.84887751 0.46265634 0.45203354]


In [31]:
print(np.random.rand(2,3))

[[0.62643773 0.94979945 0.56099027]
 [0.02941778 0.34949467 0.47520158]]


In [32]:
print(np.random.randint(1,100))

52


In [ ]:
print(np.random.randint(1,100))


14


In [34]:

print(np.random.randint(1,100,10))

[59 51 16  3 90 43 44 20 84 92]


In [35]:
print(np.random.randint(1,100,5))

[ 7 87 85 52 73]


In [ ]:
np.random.seed(0)
print(np.random.randint(1,100,5))

[45 48 65 68 68]


In [37]:
np.random.seed(0)
print(np.random.randint(1,100,5))

[45 48 65 68 68]


In [38]:
###Indexing & Slicing


In [39]:
m=np.array([1,2,3])
print(m[0])

1


In [ ]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n[0:2,1:2])     #Common things

[[2]
 [5]]


In [47]:
my_list=[1,2,3,4,5,6,7,5,6,4,6]
print(my_list[3:7])

[4, 5, 6, 7]


In [49]:
v=np.array([12,45,7,89,34])
print(v.max())
print(v.min())
print(v.argmax())
print(v.argmin())

89
7
3
2


In [50]:
A=np.array([[1,2],
            [3,4]])
B=np.array([[1,2],
            [3,4]])

print(A*B)

[[ 1  4]
 [ 9 16]]


In [ ]:
print(A@B)  #Cross product

[[ 7 10]
 [15 22]]


In [52]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
