In [2]:
import numpy as np

In [3]:
a=np.array([10,20,30,40,50])
print(a)
print(type(a))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [4]:
print(a[0])
print(a[2])

10
30


In [5]:
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.size)

(5,)
1
int64
5


In [6]:
b=np.array([
    [1,2,3],
    [4,5,6]
])

print(b.shape)   #shpae -> row by column
print(b.ndim)  #Dimension


(2, 3)
2


In [7]:
prices =np.array([100,200,300])
print(prices*2)

[200 400 600]


In [8]:
###Inititlizing Array

In [9]:
#Zero
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
print(np.ones((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [11]:
print(np.full((3,4),7))

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [12]:
###Ranges

In [13]:
#Arange
print(np.arange(5))
print(np.arange(2,9))
print(np.arange(2,9,3))

[0 1 2 3 4]
[2 3 4 5 6 7 8]
[2 5 8]


In [14]:
#Linspace
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
###Random arrays

In [16]:
print(np.random.rand(3))     #Alawyas 0 to one

[0.13777096 0.27825572 0.30279969]


In [17]:
print(np.random.rand(2,3))

[[0.08235046 0.17576005 0.91234001]
 [0.42421829 0.78199007 0.12219926]]


In [18]:
print(np.random.randint(1,100))

74


In [19]:
print(np.random.randint(1,100))


30


In [20]:

print(np.random.randint(1,100,10))

[81 85  3 87 73 17 30 76 99 53]


In [21]:
print(np.random.randint(1,100,5))

[88 34 19 55  2]


In [22]:
np.random.seed(0)
print(np.random.randint(1,100,5))

[45 48 65 68 68]


In [23]:
np.random.seed(0)
print(np.random.randint(1,100,5))

[45 48 65 68 68]


In [24]:
###Indexing & Slicing


In [25]:
m=np.array([1,2,3])
print(m[0])

1


In [26]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n[0:2,1:2])     #Common things

[[2]
 [5]]


In [27]:
my_list=[1,2,3,4,5,6,7,5,6,4,6]
print(my_list[3:7])

[4, 5, 6, 7]


In [28]:
v=np.array([12,45,7,89,34])
print(v.max())
print(v.min())
print(v.argmax())
print(v.argmin())

89
7
3
2


In [29]:
A=np.array([[1,2],
            [3,4]])
B=np.array([[1,2],
            [3,4]])

print(A*B)

[[ 1  4]
 [ 9 16]]


In [30]:
print(A@B)  #Cross product

[[ 7 10]
 [15 22]]


In [31]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
